name: Build with Gradle

on:
  create:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
  
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/libs/*.jar"
        bodyFile: "publish.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        tag: ${{ github.ref_name }}
