name: Build with Gradle

on:
  create:
    tags:
      - v*

env:
  CHANGELOG_FILE: publish.md
  PRE_RELEASE: true
  RELEASE_NAME_PREFIX: NebulaeCraftMod

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: Release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: build/libs/*.jar
 
